# Frl - Social Shopping Platform.
#
# Website: https://getfrl.com
# Official repository: https://github.com/getfrl/frl-flutter
# Author: Dylan Damsma <https://github.com/getfrl>

name: frl_flutter
description: Vote, shop, win.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  url_launcher: ^6.2.5
  google_fonts: ^6.2.0
  analyzer: ^6.2.0
  intl: ^0.18.1
  nylo_framework: ^5.21.7
  pretty_dio_logger: ^1.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dot_navigation_bar: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.1.5
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
#  lints: ^3.0.0
  flutter_test:
    sdk: flutter
  faker: ^2.1.0

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env
